M48
; DRILL file {KiCad 9.0.5} date 2025-11-06T15:21:25-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-06T15:21:25-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X111.0Y-78.5
X111.0Y-81.04
X111.3Y-65.65
X111.3Y-68.19
T2
X41.0Y-31.0
X41.0Y-87.0
X113.0Y-31.0
X113.0Y-87.0
M30
